### ISSUE TITLE
Michal Was comment 

### ISSUE THREAD

**Issue by Alessandro261188** [FisicaTre/gwas_tools#7]
"It would be interesting to list also the top 5 or 10 channel names and their corresponding rho values this might help identify the physical location or give ideas if one needs to combine the motion in two different places to explain the scattered light."

Io farei pure:
- un print di output.yml (o solo dei top 5-10) alla fine dell'analisi, senza che ogni volta devi aprire il file
- metterei i risultati di minigwas in una cartella del tipo target_channel_gps

**Comment by stfbnc** [comment]
Per il secondo punto c'è l'opzione `opath` in minigwas, non fisserei il nome della cartella

**Comment by Alessandro261188** [comment]
Ok che con opath gli dici dove mettere i file, ma se ad esempio fai più analisi con gps diversi ogni volta devi crearti una nuova cartella e spostarci i file. Un'analisi con minigwas dovrebbe metterti i risultati in una cartella. Se di default si potesse creare una cartella del tipo TARGETCHANNEL_gps, e optah li mettesse direttamente in quella cartella? Secondo me sarebbe meglio. Ad un certo punto facevi una cosa simile o sbaglio?

**Comment by stfbnc** [comment]
Chiuso con release 0.14.8

- print dei primi 10 canali con valore di rho per ogni IMF
- `minigwas` crea una cartella `target_channel_gps` dentro `opath`
